### ISSUE TITLE
Update relative times with JS

### ISSUE THREAD

**Issue by aaronpk** [kylewm/woodwind#23]
Right now it looks kind of weird to see all the posts say "3 seconds ago" as I watch new ones stream in.

Maybe using a library like https://github.com/github/time-elements

**Comment by karadaisy** [comment]
Oh good idea, I was thinking moment.js but this looks like even better. Thanks!

**Comment by karadaisy** [comment]
I went ahead and did this with moment.js and setInterval because I didn't want to dive into Custom Elements and polyfills for Firefox that github/time-elements would require. Thanks again for the suggestion!
