### ISSUE TITLE
Missing icons for syndicate-to

### ISSUE THREAD

**Issue by jeena** [kylewm/woodwind#30]
The buttons for syndication expect the names to be domain names, if they're not domain names then it looks quite odd:

![woodwind-icons](https://cloud.githubusercontent.com/assets/151764/9149785/3ec945b0-3dba-11e5-8e5f-a9975d24254c.png)

Perhaps it would be good to at least have the name as an `alt` text so it would show up if the image can not be loaded.

**Comment by kevinmarks** [comment]
this is even uglier in chrome with known
![screen shot 2016-02-05 at 10 17 25 am](https://cloud.githubusercontent.com/assets/99008/12855055/20fcfe52-cbf2-11e5-801d-0d54dc743525.png)

**Comment by karadaisy** [comment]
Try reauthorizing micropub. It should use the extended definitions now.

On Fri, Feb 5, 2016, at 10:21 AM, Kevin Marks wrote:

> this is even uglier in chrome with known screen shot 2016-02-05 at 10
> 17 25 am
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/kylewm/woodwind/issues/30#issuecomment-180481186
