### ISSUE TITLE
HTML within <noscript> is shown

### ISSUE THREAD

**Issue by jeena** [kylewm/woodwind#31]
I added lazy loading to my h-feed of photos at https://jeena.net/photos and I added `<noscript>` for browsers which aren't able to deal with the javascript loading the images on demand by scrolling.

Sadly woodwind shows the html content of the `<noscript>`-tag instead which looks weird:

![woodwind-bug](https://cloud.githubusercontent.com/assets/151764/9271235/c3089638-4278-11e5-94be-74dc6886cf0e.png)

I'm not quite sure how to deal with things like this, it makes h-feed not as apealing for now. Perhaps the readers should get the full content from the permalink instead?

**Comment by jeena** [comment]
This seem to have been reported already on IRC too:
- http://indiewebcamp.com/irc/2015-05-20/line/1432182439293
- http://indiewebcamp.com/irc/2015-05-20/line/1432183083628

**Comment by karadaisy** [comment]
You're right, this came up a few months ago with Kartik's note https://kartikprabhu.com/notes/slate-comments-fail

I tried deploying a quick hack to work around the weird behavior, let me know if it doesn't do what you expect.

**Comment by jeena** [comment]
I's definatelly nicer now, it shows the alt text of the javascript enhanced img but that is not that bad, perhaps I'll find some workaround for that too. Thanks!

![wood](https://cloud.githubusercontent.com/assets/151764/9285386/b7c0f08c-42e5-11e5-9436-05667ab10b96.png)
