### ISSUE TITLE
Explain how to start in README

### ISSUE THREAD

**Issue by jeena** [kylewm/woodwind#32]
I, and I think others too, would be able to help fix bugs and perhaps commit some features too, but it is not really obvious what we need to get it started. I guess one needs some database and it seems to be written with help of some framework which I don't recognize, a couple of lines on how to start the app would help a lot.

**Comment by karadaisy** [comment]
Sorry about this, definitely an oversight on my part! I've added the missing pieces for configuration/setup and some instructions to the README. Let me know how it goes.

**Comment by jeena** [comment]
Thanks, looks great now!
