### ISSUE TITLE
Replies count as 2 posts

### ISSUE THREAD

**Issue by LanaCoyote** [kylewm/woodwind#35]
When a reply is added to the stack of new posts not shown, it counts as 2 posts. So even if there's only one reply post waiting to be shown, the link will say "2 New Posts".

**Comment by karadaisy** [comment]
Thanks for the report, this had been bugging me too. 

Fixed in (which has been in prod for a few days before I actually committed it, whee) https://github.com/kylewm/woodwind/commit/5e334b8a056b3bb769f53d0a7b3aa83494362fd8
