### ISSUE TITLE
Failure to reply/fav/repost

### ISSUE THREAD

**Issue by rmdes** [kylewm/woodwind#46]
I got a bunch of indieweb blog subscribed into woodwind. I log in with my own website. 
I configured interaction to be based on IndiePub in the settings page. 

When I try to reply from woodwind, I just see a "Failure" message without more explanations
![screenshot_56](https://cloud.githubusercontent.com/assets/12155003/13554862/1f6ad04a-e3b3-11e5-8e15-01cb16a56557.png)

is this error/behavior due to my Known site? anything I can do to test it more thoroughly ?

**Comment by rmdes** [comment]
My indiepub plugin is enabled and this is the authorized list of apps I connected to my site, it all seems to work fine. 

![screenshot_57](https://cloud.githubusercontent.com/assets/12155003/13554961/3c573b24-e3b5-11e5-9cfa-71b25b317171.png)

**Comment by rmdes** [comment]
I tested if it was because I was using the cherwell template (might be a non-single user template) by explicitly using a single-user template but there is no way i can reply or interact with the content from within woodwind..

**Comment by karadaisy** [comment]
You could try configuring micropub again if you haven't in a while: https://woodwind.xyz/settings

Unfortunately I don't seem to have any log messages related to micropub set up in Woodwind, so I don't have any visibility into the failure. So your best bet is to open up the browser console (F12), go to the "Network" tab, and then try to publish something. You should see the response there

![micropub-response](https://cloud.githubusercontent.com/assets/950127/13555588/24315188-e379-11e5-815a-f6bd2487b81d.png)

**Comment by rmdes** [comment]
i tried several time to reconfigure, it was just adding new token access to my indiepub page on my Known so I guess it's working, Quill is working to post stuff so I guess micropub/indiepub is working.

I will try your suggestion & see if the network tab offer any hints

**Comment by rmdes** [comment]
This is what the console output : 

`{"code": 403, "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <title>Denied!</title>\n

**Comment by karadaisy** [comment]
well that is not very helpful. It looks like Known thinks the token Woodwind is using is invalid, and it refuses to authenticate it.

**Comment by rmdes** [comment]
not sure the comment above is going to help, but we definitely don't have the same response code :
![screenshot_62](https://cloud.githubusercontent.com/assets/12155003/13555641/795814d8-e3c6-11e5-8174-8d262727e843.png)

**Comment by karadaisy** [comment]
After reconfiguring micropub in Woodwind, you didn't revoke any accounts in yoursite.com/account/indiepub right?

**Comment by rmdes** [comment]
correct i was even having 2 woodwind token connected, it seems neither Known of Woodwind notice that there is already a valid token, now I revoked all access, both on woodwind setting page and on my indiepub list of connected apps on my own site. let's reconnect & see if things go better

**Comment by rmdes** [comment]
After reconnecting this is what I have :
![screenshot_63](https://cloud.githubusercontent.com/assets/12155003/13555678/4aaea3d0-e3c7-11e5-98d7-8ef4e636ce0c.png)
![screenshot_64](https://cloud.githubusercontent.com/assets/12155003/13555680/4d191bfa-e3c7-11e5-9e94-a6d8f606c594.png)

**Comment by rmdes** [comment]
Same result...
![screenshot_65](https://cloud.githubusercontent.com/assets/12155003/13555695/b0efbb8e-e3c7-11e5-93fe-4f3a3808a55a.png)

**Comment by karadaisy** [comment]
ah ha, I found a clue. your Known installation doesn't seem to like getting the micropub token via HTTP Header (Quill probably sends it via the POST body)

```
curl -i http://www.rmendes.net/micropub/endpoint -H "Authorization: Bearer 05fd..."
```

fails, while 

```
curl -i http://www.rmendes.net/micropub/endpoint?access_token=05fd...
```

succeeds

**Comment by karadaisy** [comment]
confirmed that 

```
curl -i https://kylewm.com/micropub/endpoint -H "Authorization: Bearer c98...
```

works on my site.

are you using Apache or Nginx?

**Comment by rmdes** [comment]
Nginx..

**Comment by rmdes** [comment]
So what does it mean...i mean your previous post: about getting the micropub token via HTTP Header versus POST body ?

anything i can do server side to fix this ?

**Comment by karadaisy** [comment]
Well micropub can auth in two ways: you can pass the access token in an HTTP header, `Authorization: Bearer [token]` or in the form-encoded body of the request `access_token=[token]`. For some reason, the former, which is what Woodwind uses, is not working with your site.

I'm not sure, you shouldn't have to do anything to convince nginx to pass headers through to the underlying application. You could see if there's anything in the nginx error logs but I am doubtful.

For now I've changed Woodwind to pass the access token in both ways... See if that works for you?

**Comment by rmdes** [comment]
Works great now !
i'll have a look at the nginx error log and report here if I find something related.

![screenshot_66](https://cloud.githubusercontent.com/assets/12155003/13556046/b5758fcc-e3d0-11e5-9f89-94281c154825.png)

Thanks for debugging this out !

**Comment by karadaisy** [comment]
I think the original issue should be resolved now too, thanks to @mapkyca https://github.com/idno/Known/pull/1357 . Woohoo!
