### ISSUE TITLE
HTML escaping in syndicate-to

### ISSUE THREAD

**Issue by valpackett** [kylewm/woodwind#51]
In [the new Micropub syndication targets format](http://micropub.net/draft/#syndication-targets), the `uid` field can be literally anything:

> The uid property is opaque to the client, and is the value the client sends in the Micropub request to indicate the targets to syndicate to.

I use HTML (a Bridgy Publish link) as the `uid`… which breaks Woodwind:
![screen_2016-05-06-01 51 30](https://cloud.githubusercontent.com/assets/208340/15059695/7ae81a66-1335-11e6-8003-5239ee545f98.png)

This is [vulnerable to XSS](https://www.owasp.org/index.php/XSS) — although in this case a user can only attack their own browser, putting untrusted strings directly into HTML is not a good idea.

Woodwind should escape the `uid` in the template, and unescape when sending Micropub post requests.

**Comment by karadaisy** [comment]
Thanks for the report :+1:
