### ISSUE TITLE
Logo/menu positioning suggestion

### ISSUE THREAD

**Issue by gRegorLove** [kylewm/woodwind#8]
Just a suggestion:

Setting the `h1` and the navigaiton `ul` to `display: inline-block; line-height: 64px; vertical-align: middle;` will make the navigation vertically 'center' with the logo. Sans the floats, the order of the elements would need to change too. It should wrap at lower resolutions automatically.

**Comment by karadaisy** [comment]
Thanks for the suggestion! Does it look bad to you how it is? I actually kind of like how it wraps now :)

![capture](https://cloud.githubusercontent.com/assets/950127/6159057/b86db5e0-b205-11e4-9044-6fcfe027a993.PNG)

as opposed to 

![capture2](https://cloud.githubusercontent.com/assets/950127/6159111/3dd1d752-b206-11e4-9337-f63252b68ee7.PNG)

**Comment by gRegorLove** [comment]
No, the current wrapping doesn't look bad on mobile (and my suggestion definitely takes up too much vertical space; oops). I think I'm used to seeing the logo above the navigation, but that's just a personal preference.

It was the slight vertical misalignment of the logo and the navigation links (at higher resolutions) that prompted my OCD suggestion. :]

**Comment by karadaisy** [comment]
I made the header/logo a lot smaller when you're logged in. It's less obtrusive now, and aligns/wraps more neatly. Thanks again for the suggestion!
